### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by JaPawel** [mgarciaguerrero/avocado-plugin#1]
Installed `avocado` (`npm install -g avocado`)
Installed latest version from [plugins repository](https://plugins.jetbrains.com/plugin/12092-avocado--vector-drawable-optimization).

Got this:

<img width="431" alt="error" src="https://user-images.githubusercontent.com/8151020/54872500-181d9a00-4dc5-11e9-8ab4-f02da1aa6b81.png">

In terminal: `avocado --version` returns `1.0.0` - so it is installed correctly.

Btw. Using Android Studio v3.3.2

**Comment by mgarciaguerrero** [comment]
Hi @JaPawel,
Seems that there is an issue with Mac's. I'll try to fix ASAP.
Thanks!

**Comment by mgarciaguerrero** [comment]
I've removed the plugin from jetbrains because I cannot access to environment variables from AS. Related issue:
* https://stackoverflow.com/questions/32376685/osx-android-studios-gradle-cannot-read-bash-profile-environment-variable.
